"""updated default stock to one under products and address table

Revision ID: 138712c55c48
Revises: d809285aff95
Create Date: 2025-04-03 15:43:58.592921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '138712c55c48'
down_revision = 'd809285aff95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('specific_address', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('area_town', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('city_town', sa.Text(), nullable=False))
        batch_op.drop_column('postal_code')
        batch_op.drop_column('address_line')
        batch_op.drop_column('town')
        batch_op.drop_column('is_default')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_default', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('town', sa.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('address_line', sa.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('postal_code', sa.TEXT(), nullable=True))
        batch_op.drop_column('city_town')
        batch_op.drop_column('area_town')
        batch_op.drop_column('specific_address')

    # ### end Alembic commands ###
