"""order table update for missing fielelds

Revision ID: b4e71cf596db
Revises: 138712c55c48
Create Date: 2025-04-03 16:18:15.070549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4e71cf596db'
down_revision = '138712c55c48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shipping_cost', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('discount_amount', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('shipping_method', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('tax_amount', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('delivery_company', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('tracking_number', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('delivery_person', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('estimated_delivery_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('estimated_delivery_date')
        batch_op.drop_column('delivery_person')
        batch_op.drop_column('tracking_number')
        batch_op.drop_column('delivery_company')
        batch_op.drop_column('notes')
        batch_op.drop_column('tax_amount')
        batch_op.drop_column('shipping_method')
        batch_op.drop_column('discount_amount')
        batch_op.drop_column('shipping_cost')

    # ### end Alembic commands ###
